# -*- coding: utf-8 -*-
"""mahliyo

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTGqQxiZKMg5wbo3UbMWBL4V98MaX-9L
"""

def kitoblar_nomi(belgi):
  if belgi =="Amina Shengliko'g'li":
    return "Mariya"
  elif belgi == "Ravshan Abdullao'g'li":
    return "Relslar uzra yotgan odam"
  elif belgi =="Adham Amin Nemultu":
     return "Duo taqdirni o'zgartiradi"
  elif belgi =="O'tkir Hoshimov":
     return "Ikki eshik orasi"
  elif belgi =="Abdulla Qodiriy":
     return "Mehrobdan chayon"
  elif belgi =="Fotix Duman":
     return "Men"
  elif belgi =="Ahmad Lutfiy Qozonchi":
      return "Qaynona"
  elif belgi =="Mehmet Yildiz":
      return "Izlash"
  elif belgi =="Said Chamlija":
      return "Iymon va huzun"
  elif belgi =="Iqbol Mirzo":
      return "Bonu"
  else:
    return "Googlega yozing"
belgi=input("Yozuvchi ismini kiriting")
natija=kitoblar_nomi(belgi)
print(natija)