# -*- coding: utf-8 -*-
"""tashxis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LTGqQxiZKMg5wbo3UbMWBL4V98MaX-9L
"""

def kasallik_tashxisi(belgi):
 if belgi == "Istima":
  return "Paracetamol iching"
 elif belgi == "Bosh og'rig'i":
  return "Bolnol"
 elif belgi == "Tish og'rig'i":
  return "Senepar"
 elif belgi == "Oshqozon og'rig'i":
  return "Noshpa"
 elif belgi == "Qo'l og'rig'i":
  return "Kuyupen"
 elif belgi == "Infeksiya":
  return "siproflaksalin"
 elif belgi == "Qon bosimi":
    return "Limonli suv"
  elif belgi == "Bel og'rig'i":
    return "Senepar aktiv-gel"
 else:
  return "Shifokorga murojaat qiling"

belgi=input("Shifokorga murojaat qiling")
natija = kasallik_tashxisi(belgi)
print(natija)



def kasallik_tashxisi(belgi):
    if belgi == "Istima":
        return "Paracetamol iching"
    elif belgi == "Bosh og'rig'i":
        return "Bolnol"
    elif belgi == "Tish og'rig'i":
        return "Senepar"
    elif belgi == "Oshqozon og'rig'i":
        return "Noshpa"
    elif belgi == "Qo'l og'rig'i":
        return "Kuyupen"
    elif belgi == "Infeksiya":
        return "Siproflaksalin"
    elif belgi == "Qon bosimi":
        return "Limonli suv"
    elif belgi == "Bel og'rig'i":
        return "Senepar aktiv-gel"
    else:
        return "Shifokorga murojaat qiling"

belgi = input("Kasallik belgilarini kiriting: ")
natija = kasallik_tashxisi(belgi)
print(natija)